### ISSUE TITLE
Arcade logo is not transparent and arcade marquees don't work anymore

### ISSUE THREAD

**Issue by quicksilver7837** [supersquared/es-theme-nostalgic-neo#1]
I decided to switch over to try out your enhancements but I'm having a few issues. For some reason the arcade logo is not transparent in the middle of the A,R, and D (they are filled in black, as I'd the arcade cabinet's screen in the logo). Also my marquees no longer show up properly at the top of the arcade cabinet when im browsing games in the arcade section, only the default .png shows up now.

**Comment by supersquared** [comment]
@quicksilver7837 the arcade logo has been fixed, thanks! The theme use md_marquee that just has been incorporated into EmulationStation few hours ago to display the marquee (marquee tag in your gamelist)

You have to update EmulationStation from source in Retropie menu

See the PR here: https://github.com/RetroPie/EmulationStation/pull/634

**Comment by quicksilver7837** [comment]
In the default nostalgic theme my arcade marquees show up over top of the stock arcade marquee png file. In nostalgic-neo for some reason the stock/default arcade marquee covers up all my scraped arcade marquees. I have to delete it in order to see my scraped marquees. Not a big deal except for the few arcade games that don't have a scraped marquee are now blank.

I also updated ES from source but setting the gameslist view to detailed still doesn't display marquees, only setting to video works to get them to show up.

**Comment by supersquared** [comment]
Can you send me your gamelist so I can check ?

**Comment by quicksilver7837** [comment]
Here is on of my gameslists: https://mega.nz/#!sRZhBSrR!eKAddxQWydmV_6N4dUURsOt-NWVuT2kyspKkMMZZDeU

**Comment by quicksilver7837** [comment]
It looks like this recent update is for the ES Dev branch. I'm using the stable branch which is why it's probably not working.

**Comment by supersquared** [comment]
Yes, the marquee is not available in Detailed view (only on dev branch for now), can you try in "Automatic" view instead of detailed and tell me if it's working?

**Comment by supersquared** [comment]
@quicksilver7837 did it worked with the Auto view ?

**Comment by quicksilver7837** [comment]
Im not using the dev branch so it doesnt work at all for me. Switching to the Dev branch it does work but I noticed that the screen flashes white briefly when the backgrounds are loading which looks terrible so I switched back to the stable branch for now.

**Comment by supersquared** [comment]
Yep, but try the automatic view with the stable branch, it should work

**Comment by quicksilver7837** [comment]
It doesn't work, stable branches last update was Dec 2019.
